[package]
name = "cbot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.0", features = ["full"] }
anyhow = { version = "^1.0" }
async-openai = { version = "^0.10" }
dotenv = { version = "^0.15" }